### ISSUE TITLE
Fix UnsupportedOperationException during startup

### ISSUE THREAD

**Issue by nya-elimuai** [elimu-ai/webapp#1191]
```
20:17:47.509 [main] WARN  org.hibernate.engine.jdbc.connections.internal.ConnectionProviderInitiator - HHH000181: No appropriate connection provider encountered, assuming application will be supplying connections
20:17:47.509 [main] WARN  org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator - HHH000342: Could not obtain connection to query metadata
java.lang.UnsupportedOperationException: The application must supply JDBC connections
	at org.hibernate.engine.jdbc.connections.internal.UserSuppliedConnectionProviderImpl.getConnection(UserSuppliedConnectionProviderImpl.java:44) ~[hibernate-core-5.4.26.Final.jar:5.4.26.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180) ~[hibernate-core-5.4.26.Final.jar:5.4.26.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68) ~[hibernate-core-5.4.26.Final.jar:5.4.26.Final]
```

How to reproduce: Launch the webapp locally.

**Comment by nya-elimuai** [comment]
Might be related: https://stackoverflow.com/questions/24055380/unsupportedoperationexception-the-application-must-supply-jdbc-connections

**Comment by tomaszsmy** [comment]
1580

**Comment by tomaszsmy** [comment]
https://github.com/elimu-ai/webapp/pull/1580
