### ISSUE TITLE
Handle DataIntegrityViolationException during storybook review

### ISSUE THREAD

**Issue by UmenR** [elimu-ai/webapp#1319]
**Describe the bug**
An error is thrown when trying to edit a StoryBook after adding a comment that has more than 255 words in the comment.

**To Reproduce**
1. Go to http://eng.test.elimu.ai/content/storybook/edit/28
2. Add a peer-review with a comment of more than 255 characters.
3. Click Edit.

**Expected behavior**
The changes should be persisted without throwing the error.

**Additional context**
https://github.com/elimu-ai/webapp/blob/master/src/main/java/ai/elimu/model/contributor/StoryBookContributionEvent.java#L26 does not specify a column length hence it defaults to 255 words. all models that have the comment column should ideally define its length and then further changes might be required to extend the DB column length as well.

**Comment by nya-elimuai** [comment]
> Add a comment of more than 255 words

@UmenR Is this bug referring to adding a storybook editing comment, or a peer-review comment?

<img width="355" alt="Screen Shot 2021-06-19 at 2 27 51 PM" src="https://user-images.githubusercontent.com/15718174/122642409-f847be80-d112-11eb-8b24-beb35643b732.png">

<img width="416" alt="Screen Shot 2021-06-19 at 2 27 31 PM" src="https://user-images.githubusercontent.com/15718174/122642414-fbdb4580-d112-11eb-9c39-01171485ae98.png">

**Comment by UmenR** [comment]
@nya-elimuai The issue seems to happen on both scenarios you mentioned above, Apart from that I've also tried editing a word and adding a comment while peer-reviewing a word which also gives the following error, So we need to check all places where a comment is added when providing a fix.
![Screenshot from 2021-06-19 18-35-07](https://user-images.githubusercontent.com/17663679/122643404-3eaa1700-d12d-11eb-825f-19ce14e48b86.png)

**Comment by nya-elimuai** [comment]
@UmenR Okay, good to know. Thank you for looking into this! 👍

**Comment by nya-elimuai** [comment]
For further context, I fetched the stacktrace from the server log:

```
[HIN] 13:29:07.027 [qtp1447689627-13] INFO  ai.elimu.web.content.peer_review.StoryBookPeerReviewEventCreateController - handleSubmit
[HIN] 13:29:07.028 [qtp1447689627-13] INFO  ai.elimu.web.content.peer_review.StoryBookPeerReviewEventCreateController - storyBookContributionEventId: 64
[HIN] 13:29:07.033 [qtp1447689627-13] INFO  ai.elimu.web.content.peer_review.StoryBookPeerReviewEventCreateController - storyBookContributionEvent: ai.elimu.model.contributor.StoryBookContributionEvent@5cdf6646
[HIN] 13:29:07.044 [qtp1447689627-13] WARN  org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 1406, SQLState: 22001
[HIN] 13:29:07.045 [qtp1447689627-13] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Data truncation: Data too long for column 'comment' at row 1
[HIN] 13:29:07.048 [qtp1447689627-13] ERROR ai.elimu.web.servlet.CustomSimpleMappingExceptionResolver - Resolved [org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement]
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:280) ~[spring-orm-5.3.8.jar:5.3.8]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233) ~[spring-orm-5.3.8.jar:5.3.8]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551) ~[spring-orm-5.3.8.jar:5.3.8]
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.8.jar:5.3.8]
	at com.sun.proxy.$Proxy279.create(Unknown Source) ~[?:?]
	at ai.elimu.web.content.peer_review.StoryBookPeerReviewEventCreateController.handleSubmit(StoryBookPeerReviewEventCreateController.java:60) ~[classes/:?]
```
