### ISSUE TITLE
Selenium Tests fail with latest FF

### ISSUE THREAD

**Issue by aschworer** [elimu-ai/webapp#576]
I'm not entirely sure that the reason is the Firefox version, but what I observed is:
- selenium tests are skipped during maven build, so the build is always successful
- they fail when run manually (i.e. mvn -Dtest=ErrorPageTest test)
- the version of `selenium-java` is outdated (and upgrade to the latest one requires code changes)
i guess the reason could be the outdated library trying to work with the latest FF (v.56.0)
@jo-elimuai so for now i would like to know if these tests pass for somebody, and if yes, whats the version of FF?

**Comment by aschworer** [comment]
they fail with timeout:

`org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at selenium.error_pages.ErrorPageTest.setUp(ErrorPageTest.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at selenium.ScreenshotOnFailureStatement.evaluate(ScreenshotOnFailureStatement.java:47)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)`

**Comment by jo-elimuai** [comment]
The tests do run on the headless test server We are having problems making the headless test server (CentOS Firefox 52.4.0):

```
Name        : firefox
Arch        : x86_64
Version     : 52.4.0
```

However, we are having problems with running the tests on a local computer. Running them on Mac (10.12.6) and Firefox (52.2.0) has been unsuccessful so far:

```
[INFO] Running selenium.error_pages.ErrorPageTest
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
es":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"2.0","maxVersion":"*"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true,"dependencies":[],"hasEmbeddedWebExtension":false,"mpcOptedOut":false}
1510331739207	DeferredSave.extensions.json	DEBUG	Save changes
1510331739207	addons.xpi	DEBUG	Updating database with changes to installed add-ons
1510331739207	addons.xpi-utils	DEBUG	Updating add-on states
1510331739210	addons.xpi-utils	DEBUG	Writing add-ons list
1510331739213	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/aushelper@mozilla.org.xpi
1510331739214	addons.xpi	DEBUG	Calling bootstrap method startup on aushelper@mozilla.org version 2.0
1510331739216	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1510331739217	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.10
1510331739218	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1510331739219	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.5
1510331739221	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1510331739221	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1510331739227	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1510331739228	addons.manager	DEBUG	Provider finished startup: XPIProvider
1510331739228	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1510331739228	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1510331739228	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1510331739229	addons.manager	DEBUG	Starting provider: GMPProvider
1510331739244	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1510331739245	addons.manager	DEBUG	Provider finished startup: GMPProvider
1510331739245	addons.manager	DEBUG	Starting provider: PluginProvider
1510331739246	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1510331739246	addons.manager	DEBUG	Provider finished startup: PluginProvider
1510331739247	addons.manager	DEBUG	Completed startup sequence
1510331739558	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1510331739558	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1510331739561	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1510331740060	DeferredSave.extensions.json	DEBUG	Write succeeded
1510331740060	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 19
1510331740061	DeferredSave.extensions.json	DEBUG	Starting timer
1510331740065	addons.repository	DEBUG	No addons.json found.
1510331740066	DeferredSave.addons.json	DEBUG	Save changes
1510331740072	DeferredSave.addons.json	DEBUG	Starting timer
1510331740133	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1510331740134	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1510331740134	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1510331740162	DeferredSave.extensions.json	DEBUG	Starting write
1510331740172	DeferredSave.addons.json	DEBUG	Starting write
1510331740211	DeferredSave.extensions.json	DEBUG	Write succeeded
1510331740214	DeferredSave.addons.json	DEBUG	Write succeeded
2017-11-10 17:35:42.878 plugin-container[21132:488313] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8d33, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2017-11-10 17:35:42.883 plugin-container[21132:488313] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9003, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:113)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:207)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at selenium.error_pages.ErrorPageTest.setUp(ErrorPageTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at selenium.ScreenshotOnFailureStatement.evaluate(ScreenshotOnFailureStatement.java:47)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```

**Comment by jo-elimuai** [comment]
And upgrading to Selenium version 3.7.1 produces a `NullPointerException`:

```
<dependency>
   <groupId>org.seleniumhq.selenium</groupId>
   <artifactId>selenium-java</artifactId>
   <version>3.7.1</version>
</dependency>
```

```
[INFO] Running selenium.error_pages.ErrorPageTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.264 s <<< FAILURE! - in selenium.error_pages.ErrorPageTest
[ERROR] testHttp403(selenium.error_pages.ErrorPageTest)  Time elapsed: 0.252 s  <<< ERROR!
java.lang.NullPointerException
```

**Comment by aschworer** [comment]
Hmm! All the other tests all pass, so I guess making this work locally is a matter of priorities :)
