### ISSUE TITLE
Make it possible to download APK belonging to Custom Project [8-16h]

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/webapp#605]
- [x] Add License details as parameter
- [ ] Restructure Application properties. Project --> AppCollection?
- [ ] Query by AppCollection instead of by Project
- [ ] Update https://github.com/elimu-ai/appstore/issues/125 once fixed.
- [ ] Fix NullPointerException in ApplicationVersionDaoJpa: https://github.com/elimu-ai/webapp/issues/605#issuecomment-347027825

**Comment by jo-elimuai** [comment]
Does not work when same packageName in more than one AppCollection within the same project:

```
org.springframework.dao.IncorrectResultSizeDataAccessException: result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:395)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:227)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:436)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy138.readByPackageName(Unknown Source)
	at ai.elimu.web.ApkController.handleRequest(ApkController.java:83)
```

**Comment by jo-elimuai** [comment]
Error reported by @tuancoltech: 

```
[ERROR] 2017-11-25 13:35:54,166 [ai.elimu.web.servlet.CustomSimpleMappingExceptionResolver] - Handler execution resulted in exception: java.lang.NullPointerException
java.lang.NullPointerException
        at ai.elimu.dao.jpa.ApplicationVersionDaoJpa.read(ApplicationVersionDaoJpa.java:25)
```

for URL `http://elimu.ai/apk/com.alphabetking.story.level_a-300.apk?deviceId=d814b1e6a8403bf8&checksum=943f041e75c93838e62e380e5de6a811&locale=EN&deviceModel=SM-G610F&osVersion=24&applicationId=129&appVersionCode=2000008&licenseEmail=&licenseNumber=`

See https://elimu-ai.slack.com/archives/C0LDBLX3J/p1511617013000011 for more details

**Comment by jo-elimuai** [comment]
Turns out that the java.lang.NullPointerException was due to the Android app requesting a URL containing `+` without first URL encoding it. Will be fixed as part of https://github.com/elimu-ai/appstore/issues/133
